config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	root 'welcome#index'
  resources :games

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
def index
	@games = Game.all
end
def new
	@game = Game.new
end
def create
	@game = Game.new(params[:game])
	@game.save

	redirect_to :action => :index 
end
def show
  @game = Game.find(params[:id])
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
  <title>Soccer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="ui pointing menu">
  <%= link_to 'Home', root_path, :class => "active item"%>
  <%= link_to 'Games', games_path, :class => "item"%>
  <a class="item">
    Friends
  </a>
  <div class="right menu">
    <div class="ui simple dropdown link item">
      Language
      <div class="menu">
        <a class="item">English</a>
        <a class="item">Russian</a>
        <a class="item">Spanish</a>
      </div>
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<img class="ui image" src="http://placehold.it/1600x600/c3d825/3d3d34">

<div class="ui grid">
	<div class="four wide column">
		<img class="ui image" src="http://placehold.it/500x500&text=Important">
	</div>
	<div class="twelve wide column">
		<div class="ui header">重要公告</div>
		<div class="ui fluid accordion">
		  <div class="title">
		    <i class="dropdown icon"></i>
		    What is a dog?
		  </div>
		  <div class="content">
		    <p>A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a welcome guest in many households across the world.</p>
		  </div>
		</div>
		<div class="ui divider"></div>
		<div class="ui header">最新消息</div>
	</div>
	<div class="ui inverted page grid segment">
    <div class="ten wide column">
      <div class="ui three column stackable grid">
        <div class="column">
          <div class="ui header">Courses</div>
          <div class="ui inverted link list">
            <a class="item">Registration</a>
            <a class="item">Course Calendar</a>
            <a class="item">Professors</a>
          </div>
        </div>
        <div class="column">
          <div class="ui header">Library</div>
          <div class="ui inverted link list">
            <a class="item">A-Z</a>
            <a class="item">Most Popular</a>
            <a class="item">Recently Changed</a>
          </div>
        </div>
        <div class="column">
          <div class="ui header">Community</div>
          <div class="ui inverted link list">
            <a class="item">BBS</a>
            <a class="item">Careers</a>
            <a class="item">Privacy Policy</a>
          </div>
        </div>
      </div>
    </div>
    <div class="six wide right floated aligned column">
      <h3 class="ui header">Contact Us</h3>
      <addr>
        237 Catberry Road <br>
        Milton Keynes, London <br>
      </addr>
      <p>(404) 867-5309</p>
    </div>
  </div>
</div>